// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
///import 'firebase_options.dart';

/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4EB7q2dG9t9DFsM-Ej65rYVsAoSlT31g',
    appId: '1:598912312840:web:bdb3941f7e6288c82013bd',
    messagingSenderId: '598912312840',
    projectId: 'flightdeck-v2',
    authDomain: 'flightdeck-v2.firebaseapp.com',
    storageBucket: 'flightdeck-v2.firebasestorage.app',
    measurementId: 'G-VDV00DRJMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAulXfjOrWZvk7TFIwv-IFZAwH7s6WS0iQ',
    appId: '1:598912312840:android:ef8e631f6b6a4cdd2013bd',
    messagingSenderId: '598912312840',
    projectId: 'flightdeck-v2',
    storageBucket: 'flightdeck-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTq-FRU_PPZ0jOqak0bM9SANZBSXrSpLg',
    appId: '1:598912312840:ios:c19478b1b300b36d2013bd',
    messagingSenderId: '598912312840',
    projectId: 'flightdeck-v2',
    storageBucket: 'flightdeck-v2.firebasestorage.app',
    iosBundleId: 'com.example.flightdeckFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTq-FRU_PPZ0jOqak0bM9SANZBSXrSpLg',
    appId: '1:598912312840:ios:c19478b1b300b36d2013bd',
    messagingSenderId: '598912312840',
    projectId: 'flightdeck-v2',
    storageBucket: 'flightdeck-v2.firebasestorage.app',
    iosBundleId: 'com.example.flightdeckFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4EB7q2dG9t9DFsM-Ej65rYVsAoSlT31g',
    appId: '1:598912312840:web:16461bd19965812a2013bd',
    messagingSenderId: '598912312840',
    projectId: 'flightdeck-v2',
    authDomain: 'flightdeck-v2.firebaseapp.com',
    storageBucket: 'flightdeck-v2.firebasestorage.app',
    measurementId: 'G-WXQPTQZESQ',
  );
}
